# OpenShift: keep runtime artifacts out of /etc (read-only) and use writable tmpfs.
DefaultRuntimeDir "/run/apache2"

# Avoid FQDN warning (optional)
ServerName localhost

# Run-time files in writable dirs
PidFile "/run/apache2/apache2.pid"

# log to container files
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined

# Scoreboard/lock files (avoid writing under /etc/apache2/logs)
ScoreBoardFile /run/apache2/apache_runtime_status
Mutex default:/run/apache2
