{{- $route := .Values.routes.web -}}
{{- if and $route $route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ printf "%s-%s" .Release.Name "web" }}
  labels:
    {{- include "centreon.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  to:
    kind: Service
    name: {{ printf "%s-%s" .Release.Name "web" }}
    weight: 100
  port:
    targetPort: http
  {{- if $route.host }}
  host: {{ $route.host }}
  {{- end }}
  {{- if $route.path }}
  path: {{ $route.path }}
  {{- end }}
  {{- if $route.tls }}
  tls:
    {{- toYaml $route.tls | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
