{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name $name }}
  labels:
    {{- include "centreon.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    {{- include "centreon.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    {{- range $port := $svc.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
---
{{- end }}
{{- end }}
